<a href="https://colab.research.google.com/github/andyppang/30-Days-Of-Python/blob/master/pandas120%E9%A2%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
data = {"grammer":["Python","C","Java","GO",np.nan,"SQL","PHP","Python"],
       "score":[1,2,np.nan,4,5,6,7,10]}
df = pd.DataFrame(data)
df

  grammer  score
0  Python    1.0
1       C    2.0
2    Java    NaN
3      GO    4.0
4     NaN    5.0
5     SQL    6.0
6     PHP    7.0
7  Python   10.0

WARNING: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

题目：提取含有字符串"Python"的行

In [21]:
import pandas as pd
import numpy as np
data = {"grammer":["Python","C","Java","GO",np.nan,"SQL","PHP","Python"],
       "score":[1,2,np.nan,4,5,6,7,10]}
df = pd.DataFrame(data)
# s1
df[df['grammer']=='Python']

# s2 .str 是 pandas 中的一个访问器，用于字符串类型的列。当你使用 .str
# 访问器时，它允许你执行字符串操作，比如大小写转换、去除空白、分割字符串等
results = df['grammer'].str.contains('Python')
results.fillna(value=False, inplace=True)
df[results]
# results是一个布尔序列，df[results]不能对含有空白行的布尔序列操作，要先用fillna填充

  grammer  score
0  Python    1.0
7  Python   10.0

题目：输出df的所有列名

In [22]:
import pandas as pd
import numpy as np
data = {"grammer":["Python","C","Java","GO",np.nan,"SQL","PHP","Python"],
       "score":[1,2,np.nan,4,5,6,7,10]}
df = pd.DataFrame(data)
df.columns
# df.columns: 这是一个Index对象。Index是pandas中用于索引的一种特殊数组，它具有自
# 己的属性和方法，例如排序、选择和删除。df.columns提供了DataFrame列名的索引视图，
# 可以用于索引、切片等操作。

Index(['grammer', 'score'], dtype='object')

题目：修改第二列列名为'popularity'

In [3]:
import pandas as pd
import numpy as np
data = {"grammer":["Python","C","Java","GO",np.nan,"SQL","PHP","Python"],
       "score":[1,2,np.nan,4,5,6,7,10]}
df = pd.DataFrame(data)
df.columns.values[1] = 'popularity'
df

# df.columns.values: 这是一个NumPy数组（numpy.ndarray），它是df.columns的底层
# 数据结构。当你需要将列名作为数组进行操作时，可以使用.values属性来获取列名的
# 数组表示。这在需要进行数值操作或与其他NumPy数组一起使用时非常有用。

  grammer  popularity
0  Python         1.0
1       C         2.0
2    Java         NaN
3      GO         4.0
4     NaN         5.0
5     SQL         6.0
6     PHP         7.0
7  Python        10.0

In [27]:
import pandas as pd
import numpy as np
data = {"grammer":["Python","C","Java","GO",np.nan,"SQL","PHP","Python"],
       "score":[1,2,np.nan,4,5,6,7,10]}
df = pd.DataFrame(data)
df.rename(columns={'score':"popularity"},inplace=True)
df

  grammer  popularity
0  Python         1.0
1       C         2.0
2    Java         NaN
3      GO         4.0
4     NaN         5.0
5     SQL         6.0
6     PHP         7.0
7  Python        10.0

题目：统计grammer列中每种编程语言出现的次数

In [ ]:
import pandas as pd
import numpy as np
data = {"grammer":["Python","C","Java","GO",np.nan,"SQL","PHP","Python"],
       "score":[1,2,np.nan,4,5,6,7,10]}
df = pd.DataFrame(data)